# permissions for end users to view quarkusoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quarkusoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-operator-quarkus-deploy
    app.kubernetes.io/part-of: go-operator-quarkus-deploy
    app.kubernetes.io/managed-by: kustomize
  name: quarkusoperator-viewer-role
rules:
- apiGroups:
  - wilda.fr
  resources:
  - quarkusoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wilda.fr
  resources:
  - quarkusoperators/status
  verbs:
  - get
